meta_product_name: "Elmhurst Land"
meta_title: "Elmhurst Land | Independent Property Agency"
meta_description: "An independent property agency focusing on sourcing residential development and investment opportunities within Greater London and the South-East of England"
meta_image: "meta_image.png" # should exist in `app/assets/images/`
